apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels: 
    name: vpromq01
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: vpromq01
        image: rabbitmq
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: vpromq01-port
          containerPort: 15672
        env: 
        - name: RABBITMQ_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
